package com.example.dogsbreed.model.breedlist


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Message(
    @Json(name = "affenpinscher")
    var affenpinscher: List<Any>?,
    @Json(name = "african")
    var african: List<Any>?,
    @Json(name = "airedale")
    var airedale: List<Any>?,
    @Json(name = "akita")
    var akita: List<Any>?,
    @Json(name = "appenzeller")
    var appenzeller: List<Any>?,
    @Json(name = "australian")
    var australian: List<String>?,
    @Json(name = "basenji")
    var basenji: List<Any>?,
    @Json(name = "beagle")
    var beagle: List<Any>?,
    @Json(name = "bluetick")
    var bluetick: List<Any>?,
    @Json(name = "borzoi")
    var borzoi: List<Any>?,
    @Json(name = "bouvier")
    var bouvier: List<Any>?,
    @Json(name = "boxer")
    var boxer: List<Any>?,
    @Json(name = "brabancon")
    var brabancon: List<Any>?,
    @Json(name = "briard")
    var briard: List<Any>?,
    @Json(name = "buhund")
    var buhund: List<String>?,
    @Json(name = "bulldog")
    var bulldog: List<String>?,
    @Json(name = "bullterrier")
    var bullterrier: List<String>?,
    @Json(name = "cairn")
    var cairn: List<Any>?,
    @Json(name = "cattledog")
    var cattledog: List<String>?,
    @Json(name = "chihuahua")
    var chihuahua: List<Any>?,
    @Json(name = "chow")
    var chow: List<Any>?,
    @Json(name = "clumber")
    var clumber: List<Any>?,
    @Json(name = "cockapoo")
    var cockapoo: List<Any>?,
    @Json(name = "collie")
    var collie: List<String>?,
    @Json(name = "coonhound")
    var coonhound: List<Any>?,
    @Json(name = "corgi")
    var corgi: List<String>?,
    @Json(name = "cotondetulear")
    var cotondetulear: List<Any>?,
    @Json(name = "dachshund")
    var dachshund: List<Any>?,
    @Json(name = "dalmatian")
    var dalmatian: List<Any>?,
    @Json(name = "dane")
    var dane: List<String>?,
    @Json(name = "deerhound")
    var deerhound: List<String>?,
    @Json(name = "dhole")
    var dhole: List<Any>?,
    @Json(name = "dingo")
    var dingo: List<Any>?,
    @Json(name = "doberman")
    var doberman: List<Any>?,
    @Json(name = "elkhound")
    var elkhound: List<String>?,
    @Json(name = "entlebucher")
    var entlebucher: List<Any>?,
    @Json(name = "eskimo")
    var eskimo: List<Any>?,
    @Json(name = "finnish")
    var finnish: List<String>?,
    @Json(name = "frise")
    var frise: List<String>?,
    @Json(name = "germanshepherd")
    var germanshepherd: List<Any>?,
    @Json(name = "greyhound")
    var greyhound: List<String>?,
    @Json(name = "groenendael")
    var groenendael: List<Any>?,
    @Json(name = "havanese")
    var havanese: List<Any>?,
    @Json(name = "hound")
    var hound: List<String>?,
    @Json(name = "husky")
    var husky: List<Any>?,
    @Json(name = "keeshond")
    var keeshond: List<Any>?,
    @Json(name = "kelpie")
    var kelpie: List<Any>?,
    @Json(name = "komondor")
    var komondor: List<Any>?,
    @Json(name = "kuvasz")
    var kuvasz: List<Any>?,
    @Json(name = "labrador")
    var labrador: List<Any>?,
    @Json(name = "leonberg")
    var leonberg: List<Any>?,
    @Json(name = "lhasa")
    var lhasa: List<Any>?,
    @Json(name = "malamute")
    var malamute: List<Any>?,
    @Json(name = "malinois")
    var malinois: List<Any>?,
    @Json(name = "maltese")
    var maltese: List<Any>?,
    @Json(name = "mastiff")
    var mastiff: List<String>?,
    @Json(name = "mexicanhairless")
    var mexicanhairless: List<Any>?,
    @Json(name = "mix")
    var mix: List<Any>?,
    @Json(name = "mountain")
    var mountain: List<String>?,
    @Json(name = "newfoundland")
    var newfoundland: List<Any>?,
    @Json(name = "otterhound")
    var otterhound: List<Any>?,
    @Json(name = "ovcharka")
    var ovcharka: List<String>?,
    @Json(name = "papillon")
    var papillon: List<Any>?,
    @Json(name = "pekinese")
    var pekinese: List<Any>?,
    @Json(name = "pembroke")
    var pembroke: List<Any>?,
    @Json(name = "pinscher")
    var pinscher: List<String>?,
    @Json(name = "pitbull")
    var pitbull: List<Any>?,
    @Json(name = "pointer")
    var pointer: List<String>?,
    @Json(name = "pomeranian")
    var pomeranian: List<Any>?,
    @Json(name = "poodle")
    var poodle: List<String>?,
    @Json(name = "pug")
    var pug: List<Any>?,
    @Json(name = "puggle")
    var puggle: List<Any>?,
    @Json(name = "pyrenees")
    var pyrenees: List<Any>?,
    @Json(name = "redbone")
    var redbone: List<Any>?,
    @Json(name = "retriever")
    var retriever: List<String>?,
    @Json(name = "ridgeback")
    var ridgeback: List<String>?,
    @Json(name = "rottweiler")
    var rottweiler: List<Any>?,
    @Json(name = "saluki")
    var saluki: List<Any>?,
    @Json(name = "samoyed")
    var samoyed: List<Any>?,
    @Json(name = "schipperke")
    var schipperke: List<Any>?,
    @Json(name = "schnauzer")
    var schnauzer: List<String>?,
    @Json(name = "setter")
    var setter: List<String>?,
    @Json(name = "sheepdog")
    var sheepdog: List<String>?,
    @Json(name = "shiba")
    var shiba: List<Any>?,
    @Json(name = "shihtzu")
    var shihtzu: List<Any>?,
    @Json(name = "spaniel")
    var spaniel: List<String>?,
    @Json(name = "springer")
    var springer: List<String>?,
    @Json(name = "stbernard")
    var stbernard: List<Any>?,
    @Json(name = "terrier")
    var terrier: List<String>?,
    @Json(name = "vizsla")
    var vizsla: List<Any>?,
    @Json(name = "waterdog")
    var waterdog: List<String>?,
    @Json(name = "weimaraner")
    var weimaraner: List<Any>?,
    @Json(name = "whippet")
    var whippet: List<Any>?,
    @Json(name = "wolfhound")
    var wolfhound: List<String>?
)